# Generated by Django 2.2.1 on 2019-05-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='description',
        ),
    ]
