# Generated by Django 2.2.1 on 2019-05-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
