# Generated by Django 2.2.1 on 2019-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.CharField(default='False', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
