# Generated by Django 2.2.1 on 2019-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190523_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Incomplete', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
