# Generated by Django 2.2.1 on 2019-06-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190627_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 27, 15, 37, 14, 32960)),
        ),
    ]
